Origin/shoping list
Zyabrik10/project-team-10 pull request #14
Opened 2023-06-18 06:17 UTC by NYarovenko

це тільки mobile-версія
глянь будьласко на img іконок магазинів, якось не вірно прописую шлях до них

2023-06-18 07:05 UTC, Zyabrik10 requested changes

2023-06-18 07:05 UTC, Zyabrik10 commented on src/shopping-list.css
>  @import url('./css/header.css');
Тут теж краще писати мені, щоб я добавив, бо це головні файли, які можуть не правильно потім працювати)
Але тут все добре поки що

2023-06-18 07:18 UTC, Zyabrik10 requested changes
Зроби змінни, будь-ласка

2023-06-18 07:18 UTC, Zyabrik10 commented on src/css/global.css
> +
ТРеба Не міняй цей файл, якщо треба щось змінти, пиши мені, це ж глобальний файл.
Також якщо подивитися вище файлу, то можна буде помітити, що там вже є класи ресети)
То ж використай їх, а це видали)

2023-06-18 07:18 UTC, Zyabrik10 commented on src/css/shopping-list.css
> +  font-weight: 400;
![image](https://github.com/Zyabrik10/project-team-10/assets/78109707/cf6289c4-d1dc-4416-962c-63c7f604fcbf)

Ці стилі за в body вже є. То ж видали ці, будь-ласка

2023-06-18 07:18 UTC, Zyabrik10 commented on src/css/shopping-list.css
> +  font-size: 14px;
![image](https://github.com/Zyabrik10/project-team-10/assets/78109707/25c2ec1c-7e05-4f0f-bab4-136d5fbca74e)

2023-06-18 07:18 UTC, Zyabrik10 commented on src/css/shopping-list.css
> +  color: rgba(0, 0, 0, 0.6);
![image](https://github.com/Zyabrik10/project-team-10/assets/78109707/d56474f0-6ddf-466d-8f90-479bc9be5c34)
Заміни на змінну

2023-06-18 07:18 UTC, Zyabrik10 commented on src/css/shopping-list.css
> +  border: 2px solid rgba(79, 46, 232, 0.4);
Заміни текст на змінну
![image](https://github.com/Zyabrik10/project-team-10/assets/78109707/a587d4b2-597d-4014-aa57-b257601c76c0)

2023-06-18 07:18 UTC, Zyabrik10 commented on src/css/shopping-list.css
> +  object-fit: contain;
image нема такого тегу, є img

2023-06-18 07:18 UTC, Zyabrik10 commented on src/css/shopping-list.css
> +  color: #b4afaf;
Замінни на змінну, будь-ласка
![image](https://github.com/Zyabrik10/project-team-10/assets/78109707/4d17510a-4c03-443b-b736-01efc652282e)

2023-06-18 07:18 UTC, Zyabrik10 commented on src/css/shopping-list.css
> +  overflow: auto;
overflow auto нам дає можливість, або ховати всі елементи, що не влазять в блок, або ж робити скролл. І на фокус та hover так робити дивно. Чи я щось не помітив?

2023-06-18 07:18 UTC, Zyabrik10 commented on src/js/fetch-func.js
> +axios.defaults.baseURL = 'https://books-backend.p.goit.global/books/';
Цей файл вже редагувавли і там використовували змінну, можуть бути конфлікти та баги з цим. То ж спочтаку зроби fetch до локального репозиторію, щоб зрозуміти, що там змінилося

2023-06-18 12:11 UTC, NYarovenko commented on src/css/shopping-list.css
> +  font-weight: 400;
не вийде...
те де я залишив, вони використовуються в середині тегів h2,  h3,    а вони перебивають стилі з body

2023-06-18 12:15 UTC, NYarovenko commented on src/css/shopping-list.css
> +  border: 2px solid rgba(79, 46, 232, 0.4);
+

2023-06-18 12:18 UTC, NYarovenko commented on src/js/fetch-func.js
> +axios.defaults.baseURL = 'https://books-backend.p.goit.global/books/';
це моє
я додав, коли грався, - потім видалив

2023-06-18 19:53 UTC, Zyabrik10 requested changes
Видали, будь-ласка, :root у цьому файлі, та захардкодь всі змінні, що були в цьому root як звичайне значення і я прийму pull request)

2023-06-18 19:53 UTC, Zyabrik10 commented on src/css/shopping-list.css
> +:root {
це робити не потрібно, можно було захардкодити)

2023-06-18 19:53 UTC, Zyabrik10 commented on src/css/shopping-list.css
> +  font-weight: normal;
В body вже є font-weight: 400; - теж саме шо і normal. Прибери, будь-ласка

2023-06-19 00:49 UTC, NYarovenko commented on src/css/shopping-list.css
> +:root {
зробив

2023-06-19 00:50 UTC, NYarovenko commented on src/css/shopping-list.css
> +  font-weight: normal;
якщо я це прибераю - в мене змінюється розмір шрифта

2023-06-19 11:51 UTC, Zyabrik10 approved these changes

2023-06-19 11:51 UTC, Zyabrik10 approved these changes

2023-06-19 16:36 UTC, Zyabrik10 approved these changes

2023-06-19 16:38 UTC, Zyabrik10 approved these changes

2023-06-19 16:38 UTC, Zyabrik10 commented
Я приймаю, але для початку треба конфлікти вирішити)

2023-06-19 16:50 UTC, merged