Support ukraine html css
Zyabrik10/project-team-10 pull request #6
Opened 2023-06-16 21:33 UTC by Volodya1989

SVG icons not added yet

2023-06-16 22:46 UTC, Zyabrik10 requested changes
Внесіть зміни, будь-ласка

2023-06-16 22:46 UTC, Zyabrik10 commented on src/css/extra-block.css
> +  list-style: none;
Для списку є окремий клас, який все це робить. Приберіть будь-ласка, щоб було меньше коду.
![image](https://github.com/Zyabrik10/project-team-10/assets/78109707/2702f508-e635-4bbe-bae4-9418adef4a1d)

2023-06-16 22:46 UTC, Zyabrik10 commented on src/css/extra-block.css
> +  color: #ffffff;
Замініть, будь-ласка, всі кольора на змінні

![image](https://github.com/Zyabrik10/project-team-10/assets/78109707/0add8a2c-e7cf-4cdb-bf5f-6faa7a144ed9)

2023-06-16 22:46 UTC, Zyabrik10 commented on src/css/extra-block.css
> +  text-decoration: none;
У посилань вже є такий же клас, як у списків. Будь-ласка, передевіться файл css/global.css

![image](https://github.com/Zyabrik10/project-team-10/assets/78109707/2a52e64f-fb73-4f93-a1af-eb1c8bf43c97)

2023-06-16 22:46 UTC, Zyabrik10 commented on src/css/extra-block.css
> +  letter-spacing: 0.04em;
За макетом там -0.04em, а в body вже є letter-spacing, приберіть, будь-ласка
![image](https://github.com/Zyabrik10/project-team-10/assets/78109707/c7e7c09d-6066-43f2-9f48-c477d47ec061)
![image](https://github.com/Zyabrik10/project-team-10/assets/78109707/9679d4ab-26a1-479a-acec-78965cde39fd)

2023-06-16 22:46 UTC, Zyabrik10 commented on src/partials/extra-block.html
> +      <span class="support-title">Support Ukraine</span>
Я б сказав, що це h2, а не span. Бо це важливий текст для считування. Поміняйте, будь-ласка, і додайте класс global-title, який анулює марджини. Тоді і display: block; можно там буде видалити, бо заголовки вже блочні

![image](https://github.com/Zyabrik10/project-team-10/assets/78109707/c093a80d-689a-4747-88a5-4321546439fd)
![image](https://github.com/Zyabrik10/project-team-10/assets/78109707/f4ced4cd-34ec-4084-9ed9-5acccd4bd1d8)

2023-06-16 22:46 UTC, Zyabrik10 commented on src/css/extra-block.css
> +  display: block;
ul вже є block
![image](https://github.com/Zyabrik10/project-team-10/assets/78109707/08c266fb-654b-48fd-9974-89cedf1eabc8)

2023-06-16 22:46 UTC, Zyabrik10 commented on src/css/extra-block.css
> +  font-size: 14px;
font-size в body вже 14px, це можна прибрати, щоб код був чистішим)
![image](https://github.com/Zyabrik10/project-team-10/assets/78109707/1f38db97-9d29-47de-bada-b8dfded2545e)

2023-06-16 22:46 UTC, Zyabrik10 commented on src/js/extra-block-slider.js
> +}
на 19 відриваємо скобку на 28 закриваем?
Трішки не зрозумів)

2023-06-16 23:27 UTC, Volodya1989 commented on src/css/extra-block.css
> +  list-style: none;
done

2023-06-16 23:32 UTC, Volodya1989 commented on src/css/extra-block.css
> +  letter-spacing: 0.04em;
done

2023-06-16 23:35 UTC, Volodya1989 commented on src/css/extra-block.css
> +  font-size: 14px;
done

2023-06-16 23:36 UTC, Volodya1989 commented on src/js/extra-block-slider.js
> +}
this block deleted at this time

2023-06-16 23:38 UTC, Volodya1989 commented on src/css/extra-block.css
> +  text-decoration: none;
done

2023-06-16 23:38 UTC, Volodya1989 commented on src/partials/extra-block.html
> +      <span class="support-title">Support Ukraine</span>
згідний

2023-06-16 23:45 UTC, Volodya1989 commented on src/css/extra-block.css
> +  color: #ffffff;
done

2023-06-16 23:54 UTC, Volodya1989 commented
1. Не бачу тризуба в макеті серед UI KIT та серед blocks. Будь ласка уточни щодо цього

2023-06-17 09:58 UTC, Zyabrik10 requested changes
Все правильно, лише одне треба виправити і все)

2023-06-17 09:58 UTC, Zyabrik10 commented on src/partials/extra-block.html
> +      <h2 class="support-title global-title">Support Ukraine</h2>
Треба винести h2 зі списку)

2023-06-17 16:31 UTC, merged