Header_try1_Nik
Zyabrik10/project-team-10 pull request #7
Opened 2023-06-17 03:01 UTC by t0n1ks

Maked adoptive header for mobile, desktop and tablet. Created new file JS for script  "switcher". But this not full version, I need make more fix work. This  pull maked for check dark/white theme and for can see progress task "header".

2023-06-17 09:56 UTC, Zyabrik10 requested changes
Зроби, зміни, будь-ласка

2023-06-17 09:56 UTC, Zyabrik10 commented on src/css/header.css
> +  box-sizing: border-box;
Можна видалити, вже є)

![image](https://github.com/Zyabrik10/project-team-10/assets/78109707/16721504-9561-4324-be35-1c5862600c16)

2023-06-17 09:56 UTC, Zyabrik10 commented on src/css/header.css
> +  font-family: 'DM Sans', sans-serif;
Можна видалити в body вже є

![image](https://github.com/Zyabrik10/project-team-10/assets/78109707/8e53da7f-51cb-403b-b7a4-d6b5c497b68d)

2023-06-17 09:56 UTC, Zyabrik10 commented on src/partials/header.html
> +    <script src="./js/header.js"></script>
Сюди не треба добавляти script
Треба щоб я його імпортував
Якщо треба створити js файл, кажи меня, я створю та імпортую і він буде працювати

2023-06-17 09:56 UTC, Zyabrik10 commented on src/partials/header.html
> +      <div class="header-links">
Це навігація і список.

nav>ul>li>a

2023-06-17 09:56 UTC, Zyabrik10 commented on src/partials/header.html
> +          <svg class="switcher-kolo">
Не можна називати англійськими буквами українським значенням)

2023-06-17 09:56 UTC, Zyabrik10 commented on src/partials/header.html
> -    <div class="container">
.container вже є і потрбіний, щоб по середені все було і адаптувалося

2023-06-17 09:56 UTC, Zyabrik10 commented on src/partials/header.html
> +    <link rel="stylesheet" href="./css/header.css">
Не треба сюди підключати стилі, вони вже підключені

2023-06-17 09:56 UTC, Zyabrik10 commented on src/css/header.css
> +  font-family: 'DM Sans', sans-serif;
![image](https://github.com/Zyabrik10/project-team-10/assets/78109707/8cc3554f-4c81-4ede-be6c-71c0a600529a)

2023-06-17 09:56 UTC, Zyabrik10 commented on src/css/header.css
> +.menu-button {
![image](https://github.com/Zyabrik10/project-team-10/assets/78109707/c18b4834-e86a-4839-b5e3-6ec5e0c615ce)

Видали, будь-ласка border і до кнопки додай цей клас, а потім зроби відповідні зміни, якщо щось помінялося

2023-06-19 15:04 UTC, t0n1ks commented on src/css/header.css
> +  font-family: 'DM Sans', sans-serif;
Виправленно у  гільці **fix bad and add new feach's**

2023-06-19 15:04 UTC, t0n1ks commented on src/partials/header.html
> +          <svg class="switcher-kolo">
Виправленно у  гільці **fix bad and add new feach's**

2023-06-19 15:04 UTC, t0n1ks commented on src/partials/header.html
> -    <div class="container">
Виправленно у  гільці **fix bad and add new feach's**

2023-06-19 15:04 UTC, t0n1ks commented on src/css/header.css
> +.menu-button {
Виправленно у  гільці **fix bad and add new feach's**

2023-06-19 16:33 UTC, closed without merging