Category
Zyabrik10/project-team-10 pull request #9
Opened 2023-06-17 07:36 UTC by Marlen13

Рендер книг по кліку на категорію повторюється назва категоріі

2023-06-17 09:44 UTC, Zyabrik10 requested changes
Внесіть змінни, будь-ласка.

2023-06-17 09:44 UTC, Zyabrik10 commented on src/css/catgories-list.css
> +  font-style: normal;
Це краще прибрати, бо весь текст за замовчуванням font-style: normal;

2023-06-17 09:44 UTC, Zyabrik10 commented on src/css/catgories-list.css
> +  font-weight: 400;
В body вже є font-weight: 400;

![image](https://github.com/Zyabrik10/project-team-10/assets/78109707/862e89bd-288a-4868-b871-6c958da971cf)

2023-06-17 09:44 UTC, Zyabrik10 commented on src/css/catgories-list.css
> +  color: rgba(17, 17, 17, 0.6);
Треба замінити на змінну

![image](https://github.com/Zyabrik10/project-team-10/assets/78109707/f129211f-a84b-422f-9e65-eaf9a9824059)

2023-06-17 09:44 UTC, Zyabrik10 commented on src/css/catgories-list.css
> +        color: #4F2EE8;
Теж саме

![Uploading image.png…]()

2023-06-17 09:44 UTC, Zyabrik10 commented on src/css/catgories-list.css
> +  font-family: 'DM Sans';
В body вже є font-family

![image](https://github.com/Zyabrik10/project-team-10/assets/78109707/c57e0455-5eb0-455a-aa80-2ef87d751405)

2023-06-17 09:44 UTC, Zyabrik10 commented on src/css/catgories-list.css
> +  font-style: normal;
Теж саме

2023-06-17 09:44 UTC, Zyabrik10 commented on src/css/catgories-list.css
> +  letter-spacing: -0.04em;
в body вже є letter-spacing

![image](https://github.com/Zyabrik10/project-team-10/assets/78109707/8ca5d7db-e08a-4b99-a825-47e8c79d5d90)

2023-06-17 09:44 UTC, Zyabrik10 commented on src/css/catgories-list.css
> +  color: #111111;
![image](https://github.com/Zyabrik10/project-team-10/assets/78109707/358afd83-fdd4-4dcf-95b8-066d09a49959)

2023-06-17 09:44 UTC, Zyabrik10 commented on src/partials/catalog-list.html
> +            <p class="load">LoAding....</p>
Loading, не LoAding

2023-06-17 09:44 UTC, Zyabrik10 commented on src/partials/catalog-list.html
> +            <p class= "category-list-item global-list">All categories</p>
Треба написати ще клас light-theme і зробити так в css
Також додати клас theme-switch (треба для js мені)
.category-list-item{
    все що не змініюеться з темою
}

.category-list-item.light-theme{
стилі джля світлої теми
}
.category-list-item.dark-theme{
для темної
}

2023-06-17 14:40 UTC, Marlen13 commented on src/css/catgories-list.css
> +  font-style: normal;
resolve

2023-06-17 14:40 UTC, Marlen13 commented on src/css/catgories-list.css
> +  font-weight: 400;
resolve

2023-06-17 14:45 UTC, Marlen13 commented on src/css/catgories-list.css
> +  color: rgba(17, 17, 17, 0.6);
resolve

2023-06-17 14:45 UTC, Marlen13 commented on src/css/catgories-list.css
> +        color: #4F2EE8;
resolve

2023-06-17 14:46 UTC, Marlen13 commented on src/css/catgories-list.css
> +  font-family: 'DM Sans';
resolve

2023-06-17 14:46 UTC, Marlen13 commented on src/css/catgories-list.css
> +  font-style: normal;
resolve

2023-06-17 14:46 UTC, Marlen13 commented on src/css/catgories-list.css
> +  letter-spacing: -0.04em;
resolve

2023-06-17 14:46 UTC, Marlen13 commented on src/css/catgories-list.css
> +  color: #111111;
resolve

2023-06-17 14:47 UTC, Marlen13 commented on src/partials/catalog-list.html
> +            <p class="load">LoAding....</p>
resolve

2023-06-17 14:47 UTC, Marlen13 commented on src/partials/catalog-list.html
> +            <p class= "category-list-item global-list">All categories</p>
resolve

2023-06-17 15:24 UTC, Zyabrik10 approved these changes

2023-06-17 15:25 UTC, Zyabrik10 approved these changes

2023-06-17 15:25 UTC, Zyabrik10 commented
Все чудово, але вам треба вирішити проблеми з конфліктом

2023-06-18 07:42 UTC, Zyabrik10 requested changes

2023-06-18 07:42 UTC, Zyabrik10 commented on src/js/render-category-books.js
> +// export function renderCategoryBooks() { }
розкоментуй функцію)

2023-06-18 19:55 UTC, Zyabrik10 approved these changes

2023-06-18 20:08 UTC, Zyabrik10 approved these changes

2023-06-18 20:09 UTC, Zyabrik10 approved these changes

2023-06-18 20:10 UTC, Zyabrik10 approved these changes

2023-06-18 20:10 UTC, merged